management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: INFO

spa:
  devserver:
    runner:
      enabled: true
    proxy:
      enabled: true
