management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: INFO
    ms.safi: DEBUG

spa:
  devserver:
    runner:
      enabled: false
    proxy:
      enabled: true
